SELECT 
    A.ID,
    A.GENOTYPE,
    B.PARENT_GENOTYPE
FROM ECOLI_DATA A
JOIN (
    SELECT ID, GENOTYPE AS PARENT_GENOTYPE
    FROM ECOLI_DATA
) B ON A.PARENT_ID = B.ID
    AND A.GENOTYPE & B.PARENT_GENOTYPE = B.PARENT_GENOTYPE
ORDER BY 1