SELECT DISTINCT C.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR C
LEFT OUTER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    ON C.CAR_ID = H.CAR_ID
WHERE C.car_type = '세단'
    AND MONTH(H.START_DATE) = 10
ORDER BY 1 DESC