SELECT I.ID, R.FISH_NAME, I.LENGTH
FROM FISH_INFO I
JOIN (
    SELECT A.FISH_TYPE, B.FISH_NAME, A.MAX_LENGTH
    FROM (
        SELECT
            FISH_TYPE,
            MAX(LENGTH) AS MAX_LENGTH
        FROM FISH_INFO
        GROUP BY FISH_TYPE
    ) A
    JOIN FISH_NAME_INFO B
        ON A.FISH_TYPE = B.FISH_TYPE
) R
ON I.FISH_TYPE = R.FISH_TYPE AND I.LENGTH = R.MAX_LENGTH
ORDER BY 1